# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - simple_arm_controller

  simple_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - body1_joint
      - body2_joint
      - body3_joint
      - body4_joint
      - body5_joint
    action_ns: follow_joint_trajectory
    default: true